### ISSUE TITLE
Passing a vector of only NA to Coldbir results in a vector of FALSE

### ISSUE THREAD

**Issue by LCHansson** [SwedishPensionsAgency/Coldbir#31] opened 2013-09-05 13:02 UTC
I'm passing a `data.table` to a cdb object in which one of the columns is a long vector of only NA values. However, for unknoown reasons, Coldbir saves this as a vector of FALSE values instead.

This causes problems in certain applications - for instance, I want to read an array of columns from the cdb object in which one or more columns _might_ be NA-only, and then sum up these columns using `rowSums()`, which accepts NA values but not FALSE.

**Comment by reinholdsson** [comment] 2013-11-12 10:11
This needs to be fixed. It is because it checks if the variable is logical, and then write it with 1 byte, even if it includes NA.

```
        header$type <- "logical"
        header$bytes <- 1L
        if (any(is.na(x))) {
            flog.warn("%s - logical vector; NA is converted to FALSE", name)
        }
```

We could solve it by checking for NA, and if it contains NA, then write it as a new data type (e.g. logical_NA), using 2 bytes.

**Comment by LCHansson** [comment] 2013-11-12 10:37
Sounds like a good idea. I can see why this is a good idea for most applications but not in this case. What, then is stored in the byte? I could imagine that we would actually only need one bit per row to indicate whether a value is TRUE or FALSE - what are the other 2^7 bits in that byte doing? One byte seems more than sufficient to store both TRUE/FALSE and NA/NaN since a byte can have 256 distinct values?

**Comment by reinholdsson** [comment] 2013-11-13 11:53
I was confusing bit with bytes :) You are right in that we have 256 distinct values. The problem is related to that `NA`-values are saved as `-2147483648` and because it requires 8 bytes to be stored, `NA` is converted to `FALSE` in our case.

In `midAUX` the `putV` function convert `NA` values to `-128L`. So we need to add this to `put_variable` and `get_variable`.

Example code from midAUX:

```
if(H_itemSize <= 4L){
  x <- as.integer(x)
  if(H_itemSize == 1) x[is.na(x)] <- -128L else 
  if(H_itemSize == 2) x[is.na(x)] <- -32768L
  # x[is.na(x)] <- -2147483648  for integer alreadyH_ itemSize == 4
}
```

**Comment by reinholdsson** [comment] 2013-11-19 23:08
Done! Merged into the `dev` branch.

**Closed as completed by reinholdsson** 2013-11-19 23:08 UTC
Labels: bug
